name: recetox-aplcms-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - icu
  - r-mass
  - r-rgl
  - bioconductor-mzR ==2.36.0
  - r-splines2
  - r-doparallel
  - r-foreach
  - r-snow
  - r-rcpp
  - r-arrow
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-tibble
  - r-devtools 
  - r-languageserver
  - r-jsonlite
  - r-styler
  - r-datacomparer
  - r-patrick
  - radian
  - r-httpgd
  - r-microbenchmark
  - r-covr
  - r-plyr
  - bioconductor-rawrr
  - r-purrr
